<?php

return [
    'appendicitis' => [
        'eyebrow' => 'Emergency Laparoscopic Care',
        'title' => 'Appendicitis',
        'summary' => 'Prompt evaluation and minimally invasive appendix removal focused on controlling infection and supporting a safer recovery.',
        'image' => 'assets/treatments/appendicitis-hero.png',
        'image_alt' => 'Medical illustration showing an inflamed appendix',
        'facts' => ['Duration' => '30 to 60 mins', 'Hospital stay' => '1 to 2 days', 'Typical recovery' => '1 to 2 weeks', 'Approach' => 'Laparoscopic when suitable'],
        'highlights' => ['Urgent assessment', 'Keyhole surgery', 'Infection control', 'Post-operative monitoring'],
        'overview_title' => 'What is appendicitis?',
        'overview' => 'Appendicitis is inflammation of the appendix. Pain often starts near the navel and shifts toward the lower-right abdomen as inflammation progresses. Because a severely inflamed appendix can rupture, suspected appendicitis requires urgent medical assessment.',
        'points' => [
            ['title' => 'Why it happens', 'text' => 'A blockage inside the appendix may allow bacteria to multiply, causing swelling, infection, and increasing abdominal pain.'],
            ['title' => 'Why timing matters', 'text' => 'A ruptured appendix can spread infection through the abdomen or form an abscess that needs drainage and antibiotics.'],
            ['title' => 'How it is confirmed', 'text' => 'Assessment may include an abdominal examination, blood and urine tests, ultrasound, CT, or other imaging when clinically appropriate.'],
            ['title' => 'Modern treatment', 'text' => 'Appendectomy removes the inflamed appendix. A laparoscopic approach commonly uses small incisions and a camera.'],
        ],
        'signs' => ['Pain moving toward the lower-right abdomen', 'Pain that worsens with walking or coughing', 'Nausea or vomiting', 'Loss of appetite', 'Low-grade fever', 'Abdominal bloating or bowel changes'],
        'pathway' => [
            ['title' => 'Assessment', 'text' => 'The surgeon evaluates pain, examination findings, test results, and imaging.'],
            ['title' => 'Treatment', 'text' => 'Antibiotics and appendectomy are planned according to inflammation, rupture, or abscess findings.'],
            ['title' => 'Recovery', 'text' => 'Pain control, wound care, diet progression, and activity guidance are reviewed before discharge.'],
        ],
        'faqs' => [
            ['q' => 'Is appendicitis always an emergency?', 'a' => 'Suspected appendicitis should be assessed urgently because symptoms can worsen and rupture may occur.'],
            ['q' => 'Can appendectomy be performed through keyhole surgery?', 'a' => 'Many patients are suitable for laparoscopic appendectomy, but the final approach depends on infection, rupture, abscess, and overall health.'],
            ['q' => 'When can normal activity resume?', 'a' => 'Recovery varies. Your surgeon will provide individual instructions based on the operative approach and clinical findings.'],
        ],
    ],
    'laparoscopy' => [
        'eyebrow' => 'Minimal Access Surgery',
        'title' => 'Laparoscopy',
        'summary' => 'Camera-guided diagnosis and surgery through small access points, designed to reduce tissue disruption and support earlier mobility.',
        'image' => 'assets/treatments/laparoscopy-hero.png',
        'image_alt' => 'Medical illustration of laparoscopic camera and instruments',
        'facts' => ['Duration' => '45 to 90 mins', 'Hospital stay' => 'Day care or 1 day', 'Typical recovery' => 'Procedure dependent', 'Access' => 'Small keyhole ports'],
        'highlights' => ['Small incisions', 'HD camera guidance', 'Reduced tissue handling', 'Earlier mobilisation'],
        'overview_title' => 'What is laparoscopic surgery?',
        'overview' => 'Laparoscopy uses a thin camera called a laparoscope to view the abdomen or pelvis. The same access points can be used for diagnostic assessment and for operations involving the appendix, gallbladder, hernia, and other abdominal conditions.',
        'points' => [
            ['title' => 'Clear internal view', 'text' => 'A high-definition camera magnifies the operative field and supports precise instrument movement.'],
            ['title' => 'Smaller access points', 'text' => 'Small ports usually replace the longer incision required for traditional open surgery.'],
            ['title' => 'Procedure flexibility', 'text' => 'Laparoscopy may be used to diagnose a condition, take a biopsy, or complete a planned operation.'],
            ['title' => 'Patient-specific planning', 'text' => 'Previous surgery, infection, anatomy, and medical history help determine whether laparoscopy is appropriate.'],
        ],
        'signs' => ['Gallbladder disease', 'Appendicitis', 'Selected hernias', 'Unexplained abdominal pain', 'Pelvic or abdominal assessment', 'Need for biopsy or minimally invasive surgery'],
        'pathway' => [
            ['title' => 'Pre-operative plan', 'text' => 'Clinical evaluation, investigations, fasting instructions, and anaesthesia assessment are completed.'],
            ['title' => 'Camera-guided procedure', 'text' => 'The surgeon operates through small ports while viewing magnified images on a monitor.'],
            ['title' => 'Guided recovery', 'text' => 'Patients receive mobilisation, diet, pain-control, and wound-care instructions before discharge.'],
        ],
        'faqs' => [
            ['q' => 'Does laparoscopy always mean same-day discharge?', 'a' => 'Some procedures are suitable for day care, while others require observation. The operation and your health determine the stay.'],
            ['q' => 'Will there be scars?', 'a' => 'Laparoscopy uses small access points, but every incision leaves some scar. Healing and visibility vary by patient.'],
            ['q' => 'Can every abdominal operation be laparoscopic?', 'a' => 'No. The surgeon may recommend or convert to an open approach when it is safer or technically necessary.'],
        ],
    ],
    'hernia' => [
        'eyebrow' => 'Tension-Free Repair',
        'title' => 'Hernia Surgery',
        'summary' => 'Individualised repair of abdominal-wall weakness using open or laparoscopic techniques, with mesh reinforcement when appropriate.',
        'image' => 'assets/treatments/hernia-hero.png',
        'image_alt' => 'Medical illustration of abdominal wall hernia and mesh repair',
        'facts' => ['Duration' => '45 to 90 mins', 'Hospital stay' => 'Day care or 1 day', 'Typical recovery' => '1 to 2 weeks', 'Repair' => 'Mesh when appropriate'],
        'highlights' => ['Tension-free repair', 'Open or laparoscopic options', 'Low recurrence planning', 'Early mobility guidance'],
        'overview_title' => 'What is a hernia?',
        'overview' => 'A hernia occurs when tissue pushes through a weak area in the muscle or connective tissue that normally contains it. It may appear as a bulge in the groin, navel, or a previous surgical scar and can become more noticeable with coughing, lifting, or straining.',
        'points' => [
            ['title' => 'Common types', 'text' => 'Inguinal, femoral, umbilical, incisional, and hiatal hernias occur in different anatomical locations.'],
            ['title' => 'Why they develop', 'text' => 'Muscle weakness may combine with repeated strain from lifting, coughing, constipation, pregnancy, or increased abdominal pressure.'],
            ['title' => 'How repair works', 'text' => 'The protruding tissue is returned to position and the weak area is closed, often with mesh support.'],
            ['title' => 'Why assessment matters', 'text' => 'Painful, trapped, or non-reducible hernias can indicate obstruction or loss of blood supply and require urgent care.'],
        ],
        'signs' => ['Visible groin or abdominal bulge', 'Discomfort while lifting', 'Aching or pressure at the bulge', 'Bulge increasing with coughing', 'Groin or scrotal swelling', 'Nausea or obstruction symptoms in urgent cases'],
        'pathway' => [
            ['title' => 'Diagnosis', 'text' => 'Physical examination is central. Ultrasound or CT may be used when the diagnosis or anatomy is unclear.'],
            ['title' => 'Repair selection', 'text' => 'Open or laparoscopic repair is selected according to hernia type, size, recurrence, and patient factors.'],
            ['title' => 'Recurrence prevention', 'text' => 'Wound care, gradual activity, healthy weight, constipation care, and smoking cessation support recovery.'],
        ],
        'faqs' => [
            ['q' => 'Can a hernia heal without surgery?', 'a' => 'Most adult abdominal-wall hernias do not close on their own. Observation or repair depends on symptoms and risk.'],
            ['q' => 'Is mesh always required?', 'a' => 'Mesh is commonly used for durable reinforcement, but the repair method depends on the hernia and clinical circumstances.'],
            ['q' => 'Which symptoms need emergency care?', 'a' => 'Severe pain, vomiting, abdominal distension, fever, or a firm bulge that cannot be pushed back require urgent assessment.'],
        ],
    ],
    'gallbladder' => [
        'eyebrow' => 'Laparoscopic Gallstone Care',
        'title' => 'Gallbladder Surgery',
        'summary' => 'Keyhole removal of a diseased gallbladder to treat recurring gallstone pain, inflammation, and related complications.',
        'image' => 'assets/treatments/gallbladder-hero.png',
        'image_alt' => 'Medical illustration of gallbladder and gallstones',
        'facts' => ['Duration' => '45 to 60 mins', 'Hospital stay' => 'Day care or 1 day', 'Typical recovery' => '3 to 7 days', 'Procedure' => 'Cholecystectomy'],
        'highlights' => ['Keyhole removal', 'Gallstone treatment', 'Early diet progression', 'Planned follow-up'],
        'overview_title' => 'Why is the gallbladder removed?',
        'overview' => 'The gallbladder stores bile produced by the liver. Gallstones can block bile flow and cause repeated upper-abdominal pain, inflammation, infection, jaundice, or pancreatitis. Cholecystectomy removes the gallbladder and prevents stones from forming inside it again.',
        'points' => [
            ['title' => 'Common indications', 'text' => 'Surgery may be advised for symptomatic gallstones, cholecystitis, selected polyps, bile-duct stones, or gallstone pancreatitis.'],
            ['title' => 'Laparoscopic approach', 'text' => 'A camera and fine instruments are used through small abdominal access points to separate and remove the gallbladder.'],
            ['title' => 'Life after surgery', 'text' => 'The liver continues to make bile. Most people digest normally without a gallbladder after recovery.'],
            ['title' => 'Risk discussion', 'text' => 'Bleeding, infection, bile leak, injury to nearby structures, and anaesthesia risks are reviewed before surgery.'],
        ],
        'signs' => ['Pain in the upper-right abdomen', 'Pain after fatty meals', 'Nausea or vomiting', 'Fever with abdominal pain', 'Jaundice or dark urine', 'Pain radiating toward the back or shoulder'],
        'pathway' => [
            ['title' => 'Investigation', 'text' => 'Ultrasound and blood tests assess stones, inflammation, liver function, and bile-duct concerns.'],
            ['title' => 'Cholecystectomy', 'text' => 'The gallbladder is usually removed laparoscopically under general anaesthesia.'],
            ['title' => 'Diet and activity', 'text' => 'Diet is advanced gradually and normal activity resumes according to comfort and surgeon guidance.'],
        ],
        'faqs' => [
            ['q' => 'Are gallstones removed without removing the gallbladder?', 'a' => 'For recurring gallbladder stones, removing only stones does not prevent new stones. Cholecystectomy is the standard definitive treatment for suitable patients.'],
            ['q' => 'Can I live normally without a gallbladder?', 'a' => 'Yes. The gallbladder is not essential, and most people return to a normal diet after recovery.'],
            ['q' => 'When is open surgery needed?', 'a' => 'Open surgery may be necessary when inflammation, scarring, anatomy, bleeding, or other safety concerns make keyhole surgery unsuitable.'],
        ],
    ],
    'hemorrhoids' => [
        'eyebrow' => 'Private Laser Proctology Care',
        'title' => 'Piles Treatment',
        'summary' => 'Discreet assessment and tailored treatment for internal or external hemorrhoids, from lifestyle care to office procedures and surgery.',
        'image' => 'assets/treatments/hemorrhoids-hero.png',
        'image_alt' => 'Discreet medical illustration representing laser treatment for hemorrhoids',
        'facts' => ['Duration' => '15 to 45 mins', 'Hospital stay' => 'Usually day care', 'Typical recovery' => 'Procedure dependent', 'Options' => 'Office, laser, or surgery'],
        'highlights' => ['Private consultation', 'Grade-based treatment', 'Bleeding control', 'Bowel-habit guidance'],
        'overview_title' => 'What are hemorrhoids?',
        'overview' => 'Hemorrhoids, also called piles, are swollen veins in the anus or lower rectum. Internal hemorrhoids may cause painless bleeding or prolapse, while external hemorrhoids can cause swelling, irritation, discomfort, or a painful blood clot.',
        'points' => [
            ['title' => 'Contributing factors', 'text' => 'Constipation, straining, prolonged toilet sitting, pregnancy, obesity, low-fibre diet, diarrhoea, and heavy lifting can increase pressure.'],
            ['title' => 'Treatment by grade', 'text' => 'Early disease may improve with fibre, fluids, bowel-habit changes, and medication. Persistent symptoms may need a procedure.'],
            ['title' => 'Procedure options', 'text' => 'Options can include banding, injection, coagulation, laser-based techniques, stapling, or hemorrhoidectomy.'],
            ['title' => 'Confirm the diagnosis', 'text' => 'Rectal bleeding should be assessed because other digestive conditions can produce similar symptoms.'],
        ],
        'signs' => ['Bright-red bleeding during bowel movements', 'Itching or irritation', 'Pain or discomfort', 'Swelling around the anus', 'Prolapse during bowel movement', 'A tender lump from thrombosis'],
        'pathway' => [
            ['title' => 'Private assessment', 'text' => 'Symptoms, bowel habits, examination findings, and hemorrhoid grade guide treatment.'],
            ['title' => 'Tailored procedure', 'text' => 'The least invasive suitable option is selected according to bleeding, prolapse, pain, and previous treatment.'],
            ['title' => 'Bowel-care plan', 'text' => 'Fibre, hydration, stool-softening measures, activity, and toilet-habit guidance reduce strain during healing.'],
        ],
        'faqs' => [
            ['q' => 'Does every case of piles require surgery?', 'a' => 'No. Many cases improve with lifestyle measures or office-based procedures. Surgery is reserved for selected persistent or advanced cases.'],
            ['q' => 'Is rectal bleeding always caused by piles?', 'a' => 'No. Bleeding should be medically evaluated, especially if persistent, heavy, associated with bowel changes, or unexplained weight loss.'],
            ['q' => 'How quickly can I return to work?', 'a' => 'This depends on the procedure and your symptoms. Office procedures and day-care treatments may allow earlier return than excisional surgery.'],
        ],
    ],
    'fistula' => [
        'eyebrow' => 'Sphincter-Preserving Planning',
        'title' => 'Anal Fistula Care',
        'summary' => 'Detailed mapping and individualised treatment of the fistula tract, balancing healing with protection of continence muscles.',
        'image' => 'assets/treatments/fistula-hero.png',
        'image_alt' => 'Discreet medical illustration representing treatment of an anal fistula tract',
        'facts' => ['Duration' => '30 to 60 mins', 'Hospital stay' => 'Day care or 1 day', 'Typical recovery' => '1 to 3 weeks', 'Planning' => 'Tract and sphincter based'],
        'highlights' => ['Fistula mapping', 'Abscess control', 'Continence preservation', 'Recurrence monitoring'],
        'overview_title' => 'What is an anal fistula?',
        'overview' => 'An anal fistula is an abnormal tunnel between the anal canal and the skin nearby. It commonly develops after an infected anal gland forms an abscess. The persistent tunnel may drain pus or blood and usually requires a planned procedure to heal.',
        'points' => [
            ['title' => 'How it develops', 'text' => 'An abscess may drain through the skin but leave a tract connecting the infected gland to an external opening.'],
            ['title' => 'Why mapping matters', 'text' => 'The route of the tract and its relationship to sphincter muscles determine the safest treatment option.'],
            ['title' => 'Diagnostic tools', 'text' => 'Examination, MRI, endoanal ultrasound, anoscopy, or examination under anaesthesia may be used for complex disease.'],
            ['title' => 'Treatment choices', 'text' => 'Options may include fistulotomy, seton, advancement flap, LIFT, laser closure, or other sphincter-preserving techniques.'],
        ],
        'signs' => ['An opening near the anus', 'Recurring swelling or abscess', 'Pus or blood discharge', 'Pain while sitting or passing stool', 'Skin irritation', 'Fever during active infection'],
        'pathway' => [
            ['title' => 'Control infection', 'text' => 'An acute abscess may require drainage before definitive fistula treatment.'],
            ['title' => 'Map and classify', 'text' => 'The tract is assessed to understand branches and sphincter involvement.'],
            ['title' => 'Protect healing', 'text' => 'Wound care, bowel management, follow-up, and recurrence checks continue after treatment.'],
        ],
        'faqs' => [
            ['q' => 'Can an anal fistula heal with antibiotics alone?', 'a' => 'Antibiotics may help active infection but usually do not close the persistent tract. A procedure is commonly required.'],
            ['q' => 'Why are there different fistula operations?', 'a' => 'Fistulas vary in route and muscle involvement. The operation is selected to achieve healing while reducing continence risk.'],
            ['q' => 'Can a fistula recur?', 'a' => 'Yes. Recurrence is possible, particularly with complex tracts, Crohn’s disease, branching infection, or incomplete healing.'],
        ],
    ],
    'fissure' => [
        'eyebrow' => 'Pain-Relief and Healing Care',
        'title' => 'Anal Fissure Treatment',
        'summary' => 'Private evaluation and stepwise care for a painful anal tear, focusing on softer bowel movements, muscle relaxation, and healing.',
        'image' => 'assets/treatments/fissure-hero.png',
        'image_alt' => 'Abstract medical illustration representing healing of a small tissue tear',
        'facts' => ['Consultation' => 'Private assessment', 'Hospital stay' => 'Usually day care', 'Typical recovery' => 'Treatment dependent', 'First line' => 'Bowel and medical care'],
        'highlights' => ['Pain relief', 'Constipation care', 'Muscle-spasm treatment', 'Surgery only when needed'],
        'overview_title' => 'What is an anal fissure?',
        'overview' => 'An anal fissure is a small tear in the lining of the anus. It often follows passage of a hard or large stool and can cause sharp pain, bleeding, and muscle spasm during or after bowel movements.',
        'points' => [
            ['title' => 'Common causes', 'text' => 'Constipation, hard stool, straining, chronic diarrhoea, and childbirth can injure the anal lining.'],
            ['title' => 'Acute and chronic fissures', 'text' => 'Recent fissures often heal with conservative care. A fissure lasting more than several weeks may need further treatment.'],
            ['title' => 'Non-surgical care', 'text' => 'Fibre, fluids, stool softening, sitz baths, and prescribed medicines can reduce trauma and sphincter spasm.'],
            ['title' => 'Procedure options', 'text' => 'Selected chronic fissures may be treated with injection therapy or lateral internal sphincterotomy after risk assessment.'],
        ],
        'signs' => ['Sharp pain during bowel movement', 'Pain lasting after bowel movement', 'Bright-red blood on tissue', 'A visible small tear', 'Muscle spasm', 'Skin tag near a chronic fissure'],
        'pathway' => [
            ['title' => 'Identify triggers', 'text' => 'The consultation reviews constipation, diarrhoea, childbirth, inflammatory disease, and previous treatment.'],
            ['title' => 'Break the pain cycle', 'text' => 'Stool-softening and muscle-relaxing measures reduce repeated tearing and support blood flow.'],
            ['title' => 'Escalate carefully', 'text' => 'Persistent fissures are reassessed before injection or surgery is considered.'],
        ],
        'faqs' => [
            ['q' => 'Can a fissure heal without surgery?', 'a' => 'Yes. Many acute fissures heal with fibre, fluids, stool-softening measures, sitz baths, and prescribed medication.'],
            ['q' => 'Why does pain continue after bowel movement?', 'a' => 'The tear can trigger spasm of the internal anal sphincter, reducing blood flow and prolonging pain.'],
            ['q' => 'When is surgery considered?', 'a' => 'Surgery may be discussed for chronic fissures that do not heal with appropriate medical treatment.'],
        ],
    ],
    'endoscopy' => [
        'eyebrow' => 'Upper GI Diagnostics',
        'title' => 'Endoscopy',
        'summary' => 'Direct camera examination of the oesophagus, stomach, and duodenum for diagnosis, biopsy, and selected treatments.',
        'image' => 'assets/treatments/endoscopy-hero.png',
        'image_alt' => 'Medical illustration of an upper gastrointestinal endoscope',
        'facts' => ['Duration' => '15 to 30 mins', 'Observation' => 'Usually a few hours', 'Recovery' => 'Same day', 'Capability' => 'Diagnosis and treatment'],
        'highlights' => ['Direct visual examination', 'Biopsy when required', 'Sedation options', 'Same-day reporting'],
        'overview_title' => 'What is upper GI endoscopy?',
        'overview' => 'Upper gastrointestinal endoscopy uses a flexible camera to examine the oesophagus, stomach, and first part of the small intestine. It helps investigate symptoms, identify inflammation or bleeding, take biopsies, and perform selected treatments.',
        'points' => [
            ['title' => 'Investigate symptoms', 'text' => 'Endoscopy may be advised for persistent heartburn, swallowing difficulty, vomiting, upper-abdominal pain, anaemia, or digestive bleeding.'],
            ['title' => 'Obtain tissue samples', 'text' => 'Small biopsies can be taken through the scope to evaluate inflammation, infection, coeliac disease, or suspicious areas.'],
            ['title' => 'Treat selected problems', 'text' => 'Tools passed through the scope can control bleeding, widen narrowing, remove foreign bodies, or treat selected lesions.'],
            ['title' => 'Comfort and safety', 'text' => 'Throat spray, sedation, monitoring, fasting, medication review, and an escort plan are discussed before the procedure.'],
        ],
        'signs' => ['Persistent acidity or heartburn', 'Difficulty or pain while swallowing', 'Repeated vomiting', 'Unexplained upper-abdominal pain', 'Anaemia or suspected bleeding', 'Black stool or vomiting blood requiring urgent care'],
        'pathway' => [
            ['title' => 'Preparation', 'text' => 'Fasting and medication instructions are provided. Blood-thinning medicines require specific review.'],
            ['title' => 'Examination', 'text' => 'The flexible camera examines the upper digestive tract while vital signs are monitored.'],
            ['title' => 'Results', 'text' => 'Initial findings are discussed after recovery; biopsy results require additional laboratory time.'],
        ],
        'faqs' => [
            ['q' => 'Is endoscopy painful?', 'a' => 'Most patients tolerate it with throat spray and/or sedation. Temporary throat discomfort or bloating can occur.'],
            ['q' => 'Can I drive after sedation?', 'a' => 'No. If sedation is used, arrange an adult escort and avoid driving or important decisions for the advised period.'],
            ['q' => 'Does a normal endoscopy rule out every digestive condition?', 'a' => 'No. Some conditions require biopsy, imaging, laboratory tests, or examination of other parts of the digestive system.'],
        ],
    ],
    'thyroid' => [
        'eyebrow' => 'Endocrine Surgery',
        'title' => 'Thyroid Surgery',
        'summary' => 'Careful evaluation and surgery for selected thyroid nodules, goitre, overactive thyroid, and suspected or confirmed cancer.',
        'image' => 'assets/treatments/thyroid-hero.png',
        'image_alt' => 'Medical illustration highlighting the thyroid gland',
        'facts' => ['Duration' => '60 to 120 mins', 'Hospital stay' => '1 to 2 days', 'Typical recovery' => '1 to 2 weeks', 'Planning' => 'Nodule and hormone based'],
        'highlights' => ['Ultrasound-led planning', 'Voice-nerve protection', 'Cosmetic neck closure', 'Hormone follow-up'],
        'overview_title' => 'When is thyroid surgery considered?',
        'overview' => 'The thyroid is a butterfly-shaped gland at the front of the neck that regulates metabolism. Surgery may be considered for suspicious nodules, thyroid cancer, a large or compressive goitre, or selected cases of hyperthyroidism.',
        'points' => [
            ['title' => 'Pre-operative evaluation', 'text' => 'Ultrasound, thyroid-function tests, needle biopsy, and voice assessment may be used according to the condition.'],
            ['title' => 'Extent of surgery', 'text' => 'A thyroid lobectomy removes one side, while total thyroidectomy removes the whole gland when clinically indicated.'],
            ['title' => 'Structures protected', 'text' => 'Careful dissection protects the recurrent laryngeal nerves and parathyroid glands located close to the thyroid.'],
            ['title' => 'After surgery', 'text' => 'Calcium levels, voice, wound healing, pathology, and thyroid-hormone replacement are reviewed as needed.'],
        ],
        'signs' => ['Neck lump or enlarging thyroid', 'Difficulty swallowing', 'Pressure or breathing symptoms', 'Voice change', 'Overactive-thyroid symptoms', 'Suspicious ultrasound or biopsy findings'],
        'pathway' => [
            ['title' => 'Characterise the thyroid', 'text' => 'Clinical examination, hormone tests, ultrasound, and biopsy define the condition and surgical need.'],
            ['title' => 'Precision surgery', 'text' => 'The planned thyroid tissue is removed while protecting nearby nerves and parathyroid glands.'],
            ['title' => 'Long-term review', 'text' => 'Pathology, thyroid hormone, calcium, scar care, and further specialist follow-up are coordinated.'],
        ],
        'faqs' => [
            ['q' => 'Will I need thyroid medicine after surgery?', 'a' => 'After total thyroidectomy, lifelong thyroid hormone is required. After lobectomy, the remaining gland may or may not produce enough hormone.'],
            ['q' => 'Can thyroid surgery affect the voice?', 'a' => 'Temporary voice change can occur. Permanent nerve injury is uncommon but is an important risk discussed before surgery.'],
            ['q' => 'How visible is the scar?', 'a' => 'The incision is usually placed in a natural neck crease. Scar appearance varies and improves over time.'],
        ],
    ],
    'breast-surgery' => [
        'eyebrow' => 'Compassionate Breast Care',
        'title' => 'Breast Surgery',
        'summary' => 'Respectful assessment and surgical care for breast lumps, infection, nipple symptoms, benign disease, and suspected cancer.',
        'image' => 'assets/treatments/breast-surgery-hero.png',
        'image_alt' => 'Respectful medical illustration representing breast assessment',
        'facts' => ['Consultation' => 'Clinical assessment', 'Imaging' => 'Age and symptom based', 'Biopsy' => 'When indicated', 'Treatment' => 'Diagnosis specific'],
        'highlights' => ['Private examination', 'Triple assessment', 'Tissue-preserving planning', 'Clear pathology follow-up'],
        'overview_title' => 'When should breast symptoms be assessed?',
        'overview' => 'Breast symptoms are common and many causes are benign, but a new lump, persistent pain, nipple discharge, skin change, or infection should be assessed. Evaluation combines clinical examination with imaging and biopsy when required.',
        'points' => [
            ['title' => 'Common conditions', 'text' => 'Care includes fibroadenoma, fibrocystic change, cysts, abscess or mastitis, nipple discharge, phyllodes tumour, and breast cancer.'],
            ['title' => 'Triple assessment', 'text' => 'Clinical examination, imaging, and needle sampling are combined when necessary to reach a reliable diagnosis.'],
            ['title' => 'Surgical planning', 'text' => 'The procedure is selected according to diagnosis, size, location, pathology, cosmetic considerations, and patient preference.'],
            ['title' => 'Coordinated follow-up', 'text' => 'Pathology review and referral to oncology or other specialists are arranged when additional treatment is required.'],
        ],
        'signs' => ['A new breast lump', 'Persistent focal breast pain', 'Painful swelling or redness', 'Nipple discharge', 'Skin puckering or dimpling', 'Change in nipple position or breast shape'],
        'pathway' => [
            ['title' => 'Private consultation', 'text' => 'Symptoms, family history, examination findings, and previous imaging are reviewed respectfully.'],
            ['title' => 'Imaging and biopsy', 'text' => 'Ultrasound, mammography, MRI, or needle biopsy may be selected according to age and findings.'],
            ['title' => 'Individual treatment', 'text' => 'Observation, drainage, lump removal, breast-conserving surgery, or referral is planned from the confirmed diagnosis.'],
        ],
        'faqs' => [
            ['q' => 'Does every breast lump mean cancer?', 'a' => 'No. Many lumps are benign, but a new or changing lump should be examined and imaged appropriately.'],
            ['q' => 'When is a biopsy needed?', 'a' => 'A biopsy is recommended when examination or imaging cannot confidently confirm a benign cause or when suspicious features are present.'],
            ['q' => 'Can benign breast lumps be observed?', 'a' => 'Some benign lumps can be monitored. Growth, symptoms, imaging features, diagnosis, and patient preference guide the decision.'],
        ],
    ],
];
